---

- name: Deploy Ollama container
  docker_container:

    name: ollama

    image: ollama/ollama

    state: started

    restart_policy: always

    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama


- name: Wait for Ollama service
  wait_for:

    host: localhost

    port: 11434

    timeout: 60


- name: Pull AI model
  command: docker exec ollama ollama pull llama3.2:3b
