pipeline {

    agent any

    options {
        disableConcurrentBuilds()
    }


    environment {

        AWS_DEFAULT_REGION = 'us-east-1'

    }


    stages {


        stage('Checkout') {

            steps {

                git branch: 'main',
                    url: 'https://github.com/Hemanthmahendrakar/AI-ChatOps-Automation.git'

            }

        }



        stage('AWS Authentication') {

            steps {

                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-creds'
                    ]
                ]) {

                    sh '''

                    echo "Checking AWS credentials..."

                    aws configure set region $AWS_DEFAULT_REGION

                    aws sts get-caller-identity

                    '''

                }

            }

        }



        stage('Terraform Init') {

            steps {

                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-creds'
                    ]
                ]) {

                    sh '''

                    echo "Terraform Init"

                    cd terraform

                    terraform init -reconfigure

                    '''

                }

            }

        }



        stage('Terraform Plan') {

            steps {

                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-creds'
                    ]
                ]) {

                    sh '''

                    echo "Terraform Plan"

                    cd terraform

                    terraform plan -out=tfplan

                    '''

                }

            }

        }




        stage('Terraform Apply') {

            steps {

                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-creds'
                    ]
                ]) {

                    sh '''

                    echo "Terraform Apply"

                    cd terraform

                    terraform apply -auto-approve tfplan

                    '''

                }

            }

        }





        stage('Get Terraform Outputs') {

            steps {

                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-creds'
                    ]
                ]) {

                    sh '''

                    echo "Reading Terraform outputs"


                    cd terraform


                    OPENWEBUI_IP=$(terraform output -raw openwebui_public_ip)

                    OLLAMA_IP=$(terraform output -raw ollama_public_ip)



                    echo "OpenWebUI IP: $OPENWEBUI_IP"

                    echo "Ollama IP: $OLLAMA_IP"



                    cd ../ansible



                    sed -i "s/OPENWEBUI_IP/$OPENWEBUI_IP/g" inventory.ini

                    sed -i "s/OLLAMA_IP/$OLLAMA_IP/g" inventory.ini



                    echo "Updated Inventory"

                    cat inventory.ini


                    '''

                }

            }

        }





        stage('Wait for SSH') {

            steps {

                sh '''

                echo "Waiting for EC2 SSH readiness..."


                OPENWEBUI_IP=$(cd terraform && terraform output -raw openwebui_public_ip)


                for i in {1..30}

                do


                    echo "Checking SSH attempt $i"


                    if nc -z $OPENWEBUI_IP 22

                    then

                        echo "SSH is ready on $OPENWEBUI_IP"

                        exit 0

                    fi


                    echo "SSH not ready yet..."

                    sleep 10


                done



                echo "SSH failed to become available"

                exit 1


                '''

            }

        }







        stage('Ansible Deploy') {


            steps {


                sshagent(['ec2-key']) {


                    sh '''

                    echo "Running Ansible Deployment"



                    cd ansible



                    ansible-playbook \
                    -i inventory.ini \
                    playbook.yml \
                    -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"



                    '''

                }

            }

        }


    }




    post {


        success {


            echo """

            =================================

            Deployment completed successfully

            =================================

            """

        }



        failure {


            echo """

            =================================

            Deployment failed. Check logs

            =================================

            """

        }


    }

}
